data_dir = "/var/lib/vector"

[api]
enabled = true

[sources.nginx]
type = "file"
include = [ "/var/log/nginx.log" ]
read_from = "beginning"

[sinks.s3]
type = "aws_s3"
inputs = [ "nginx" ]
bucket = "singlelog-logs"
key_prefix = "nginx/"
compression = "none"
region = "us-east-1"
auth.access_key_id = ""
auth.secret_access_key = ""

[sinks.s3.encoding]
  codec = "text"
