data_dir = "/var/lib/vector"

[api]
enabled = true

[sources.nginx]
type = "file"
include = [ "/var/log/nginx/access.log" ]
read_from = "beginning"

[sinks.s3]
type = "aws_s3"
inputs = [ "nginx" ]
bucket = "singlelogs-logs"
key_prefix = "nginx/"
compression = "none"
region = "eu-west-1"
batch.timeout_secs = 60 # default is 300 seconds

[sinks.s3.encoding]
  codec = "text"


